# Generated by Django 5.2.3 on 2025-06-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teachersubjectclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
            ],
        ),
    ]
