# Generated by Django 5.2.3 on 2025-07-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='cat1',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='cat2',
        ),
    ]
