# Generated by Django 5.2.3 on 2025-07-10 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
