# Generated by Django 5.2.3 on 2025-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='SCHOOL MANAGEMENT SYSTEM', max_length=200)),
                ('po_box', models.CharField(default='P.O. Box: 12345 - 00100', max_length=50)),
                ('phone', models.CharField(default='TEL: 020-1234567 / 0720-123456', max_length=50)),
                ('location', models.CharField(default='NAIROBI', max_length=100)),
                ('email', models.EmailField(default='info@schoolms.com', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
            },
        ),
    ]
